### ISSUE TITLE
Enable Bias-T

### ISSUE THREAD

**Issue by rchadgray** [roger-/pyrtlsdr#128]
I do not see a way to enable bias-t to power other things in line with rtl-sdr.

Is there a way to do this?

Thanks!
Chad

**Comment by nocarryr** [comment]
Pull request #123 adds bias-t control, but it was waiting on a response from the author.  Let me see if I can get it moving so it can be merged

**Comment by bradylangdale** [comment]
@rchadgray 

PR: #123 got merged. It worked for me back when I was needing it.

**Comment by nocarryr** [comment]
Thanks @bradylangdale 

I'm working on adding automated deployments for GH Actions, but until then you should be able to work with bias-t from cloning this repo
