### ISSUE TITLE
Pip install pyrtlsdr error

### ISSUE THREAD

**Issue by kornos** [roger-/pyrtlsdr#42]
Ubuntu 14.10 , kernel 4.5.2
This morning I tried to install pyrtlsdr via pip install, I got this error:

kornos@ubuntu:~/projects/SDR/pyrtlsdr$ sudo pip install pyrtlsdr
Downloading/unpacking pyrtlsdr
  Downloading pyrtlsdr-0.2.2-py2-none-any.whl
Installing collected packages: pyrtlsdr
Compiling /tmp/pip-build-1mYngd/pyrtlsdr/rtlsdr/rtlsdraio.py ...
  File "/tmp/pip-build-1mYngd/pyrtlsdr/rtlsdr/rtlsdraio.py", line 24
    def __init__(self, func_start, func_stop=None, queue_size=20, *, loop=None):
                                                                   ^
SyntaxError: invalid syntax

Successfully installed pyrtlsdr
Cleaning up...

Running RtlSdrScanner after this produced all kind of weird errors.(segfaults,etc)
Pip uninstall and after that git clone pyrtlsdr fixed it.

Sorry if I report in the wrong place , but I think pip install rtlsdr is flawed.

Thanks
Victor

**Comment by nocarryr** [comment]
That's an issue with a module meant for a later python version (3.5).  It uses keywords that don't exist in older versions so it's *supposed* to be excluded from packages for the incompatible versions.

I checked the wheel file (`pyrtlsdr-0.2.2-py2-none-any.whl`) and verified that it somehow made its way back in there so I'll have do some digging and figure out why.

Thanks for bringing this up

**Comment by kornos** [comment]
Wow, you must be the fastest bugfixer I saw so far :-O

Best regards
Victor

**Comment by nocarryr** [comment]
Lol, putting off doing yard work. :laughing:

**Comment by nocarryr** [comment]
Should be fixed from PR #43 and now released to PyPI as v0.2.3

@kornos Let me know if that didn't work for you

**Comment by kornos** [comment]
Yep , it works like a charm now.

Thanks very much.
