### ISSUE TITLE
Does not work on 64-bit python.

### ISSUE THREAD

**Issue by chibill** [roger-/pyrtlsdr#63]
I can't get pyrtlsdr to work on 64-bit python. I am 99% sure its not a pyrtlsdr problem but a problem with librtlsdr not being compiled for 64-bit And they don't offer 64-bit builds on the new one. :( . But I am still opening an issue here in case someone also has the problem.

**Comment by nocarryr** [comment]
Have you tried building librtlsdr from source? I know there isn't much documentation out there on building for windows, but I just stumbled on this:
https://github.com/librtlsdr/librtlsdr/tree/master/win32-qtcreator

The readme seems to have at least a bit of info to get things rolling.
I would also recommend opening an issue on [librtlsdr](https://github.com/librtlsdr/librtlsdr) to see if they have a way of including x64 builds in their releases.  I can't tell exactly how they're doing the builds at first glance, but it seems they've got it going for quite a few platforms.

**Comment by chibill** [comment]
I made in issue on there end but they have not responded yet.

**Comment by chibill** [comment]
Well this sort of sucks... They have not responded to anyone in over a week.... And I don't want to downgrade my python to 32 bit on my 64 bit machine... :(

So currently I can't use this lib :(

**Comment by chibill** [comment]
Okay. One of the devs says they will try building it for 64-bit tomorrow... 

Apparently they did not build it for 64-bit because most people only give out 32 bit.....

https://github.com/librtlsdr/librtlsdr/issues/51
