### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by piotr-koca** [roger-/pyrtlsdr#83]
Hello,

There is a typo in inline documentation in following [section](https://github.com/roger-/pyrtlsdr/blob/7866fdd95e61f98947ab395a144430fa22162677/rtlsdr/rtlsdr.py#L181):

```
    def init_device_values(self):
        """Retrieves information from the device

        This method acquires the values for :attr:`gain_values`. Also sets the
        device to the default :attr:`center frequency <DEFAULT_RS>`, the
        :attr:`sample rate <DEFAULT_FC>` and :attr:`gain <DEFAULT_GAIN>`
        """
```

I think **DEFAULT_RS** and **DEFAULT_FC** should be swapped.

Best regards!

**Comment by nocarryr** [comment]
Oops!  Great catch.  Would you like to make the change and submit a pull request?
