### ISSUE TITLE
Strange error running pyrtlsdr example

### ISSUE THREAD

**Issue by wangshujun1** [roger-/pyrtlsdr#95]
>>> from rtlsdr import RtlSdr

sdr = RtlSdr()

# configure device
sdr.sample_rate = 2.048e6  # Hz
sdr.center_freq = 70e6     # Hz
sdr.freq_correction = 60   # PPM
sdr.gain = 'auto'

print(sdr.read_samples(512))

>>> %Run read.py
  File "/home/pi/Documents/read.py", line 1
    Python 3.5.3 (default, Jan 19 2017, 14:11:04)
             ^
SyntaxError: invalid syntax

I just copied the code in readme.md and successfully installed setup.py. Is this something wrong with librtlsdr?
I'm very new to python and pyrtlsdr, hope someone can help

**Comment by wangshujun1** [comment]
btw i test.py and demo_waterfall work well

**Comment by wangshujun1** [comment]
no one??

**Comment by roger-** [comment]
Can you post the entire code?

Are you missing an import at the top?

**Comment by wangshujun1** [comment]
> Run the code from a terminal using 'python read.py' instead.

It did not work and shown the same error

**Comment by nocarryr** [comment]
It seems likely that there's a copy-paste issue.  Can you paste the contents of `read.py` as a code block?

Start the code block with three backticks:
\```

Then paste your code on the next line and end with another triple backtick line \```

https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code

**Comment by nocarryr** [comment]
It looks like this is what you originally pasted:

```python
>>> from rtlsdr import RtlSdr

sdr = RtlSdr()

# configure device
sdr.sample_rate = 2.048e6  # Hz
sdr.center_freq = 70e6     # Hz
sdr.freq_correction = 60   # PPM
sdr.gain = 'auto'

print(sdr.read_samples(512))
```

If that's the case, the first line is what's causing problems.  Just remove the `>>> `  and any spaces on that line so it looks like:
```python
from rtlsdr import RtlSdr
```

**Comment by wangshujun1** [comment]
> It looks like this is what you originally pasted:
> 
> ```python
> >>> from rtlsdr import RtlSdr
> 
> sdr = RtlSdr()
> 
> # configure device
> sdr.sample_rate = 2.048e6  # Hz
> sdr.center_freq = 70e6     # Hz
> sdr.freq_correction = 60   # PPM
> sdr.gain = 'auto'
> 
> print(sdr.read_samples(512))
> ```
> 
> If that's the case, the first line is what's causing problems. Just remove the `>>> ` and any spaces on that line so it looks like:
> 
> ```python
> from rtlsdr import RtlSdr
> ```

still did not work

**Comment by wangshujun1** [comment]
ohhh  I fixed it!
I found that error is ''Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170124] on linux
Type "copyright", "credits" or "license()" for more information.'' which created by Python itself. It worked after I deleted this. Thanks for the help!
